# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inside_ui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(950, 600)
        self.back = QtWidgets.QLabel(Form)
        self.back.setGeometry(QtCore.QRect(0, 0, 950, 600))
        self.back.setText("")
        self.back.setPixmap(QtGui.QPixmap("back1.jpg"))
        self.back.setScaledContents(True)
        self.back.setObjectName("back")
        self.inbox = QtWidgets.QPushButton(Form)
        self.inbox.setGeometry(QtCore.QRect(10, 60, 197, 51))
        self.inbox.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton:Hover{background-color:rgba(173,216,230,0.4)}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inbox.setIcon(icon)
        self.inbox.setIconSize(QtCore.QSize(25, 25))
        self.inbox.setObjectName("inbox")
        self.compose = QtWidgets.QPushButton(Form)
        self.compose.setGeometry(QtCore.QRect(10, 111, 197, 51))
        self.compose.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton:Hover{background-color:rgba(173,216,230,0.4);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compose.setIcon(icon1)
        self.compose.setIconSize(QtCore.QSize(25, 25))
        self.compose.setObjectName("compose")
        self.sent = QtWidgets.QPushButton(Form)
        self.sent.setGeometry(QtCore.QRect(10, 162, 197, 51))
        self.sent.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton:Hover{background-color:rgba(173,216,230,0.4);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sent.setIcon(icon)
        self.sent.setIconSize(QtCore.QSize(30, 30))

        self.junk = QtWidgets.QPushButton(Form)
        self.junk.setGeometry(QtCore.QRect(10, 213, 197, 51))
        self.junk.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton:Hover{background-color:rgba(173,216,230,0.4);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("junk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.junk.setIcon(icon)
        self.junk.setIconSize(QtCore.QSize(25, 25))

        self.thrash = QtWidgets.QPushButton(Form)
        self.thrash.setGeometry(QtCore.QRect(10, 264, 197, 51))
        self.thrash.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton:Hover{background-color:rgba(173,216,230,0.4);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("thrash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.thrash.setIcon(icon)
        self.thrash.setIconSize(QtCore.QSize(25, 25))

        self.out = QtWidgets.QPushButton(Form)
        self.out.setGeometry(QtCore.QRect(10, 315, 197, 51))
        self.out.setStyleSheet("QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton{background-color:rgba(255,255,255,0);color:white;font-size:16pt;}QPushButton:Hover{background-color:rgba(173,216,230,0.4);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.out.setIcon(icon)
        self.out.setIconSize(QtCore.QSize(25, 25))

        self.search = QtWidgets.QLineEdit(Form)
        self.search.setGeometry(QtCore.QRect(345, 0, 461, 28))
        self.search.setStyleSheet("border-radius:1px;background-color:rgba(173,216,230,0.4);color:black;")
        self.search.setPlaceholderText('Search')

        self.scrollAreaWidgetContents = QtWidgets.QWidget(Form)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(208, 60, 730, 539))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.mails = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.mails.resize(732,541)
        self.mails.setContentsMargins(0, 0, 0, 0)
        self.mails.setObjectName("mails")
        self.mails.setStyleSheet('color:white;font-size:16pt;background-color:rgba(173,216,230,0.4)')
        self.mails.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.label=QLabel(Form)
        self.label.setGeometry(17,0,41,41)
        self.label.setScaledContents(True)
        self.label.setPixmap(QPixmap('mail-icon.png'))
        self.nm = QLabel(Form)
        self.nm.setText('PyWebmail')
        self.nm.move(65,5)
        self.nm.setStyleSheet('font-size:24pt')
        self.nex=QPushButton(Form)
        self.nex.setGeometry(826,30,113,32)
        self.nex.setText('Next')
        self.sa = QPushButton(Form)
        self.sa.setGeometry(356, 30, 113, 32)
        self.sa.setText('Select All')
        self.cs = QPushButton(Form)
        self.cs.setGeometry(513, 30, 113, 32)
        self.cs.setText('Clear Sel')
        self.de = QPushButton(Form)
        self.de.setGeometry(669, 30, 113, 32)
        self.de.setText('Delete')
        self.pre = QPushButton(Form)
        self.pre.setGeometry(200, 30, 113, 32)
        self.pre.setText('Prev')
        self.ba = QPushButton(Form)
        self.ba.setGeometry(200, 30, 113, 32)
        self.ba.setText('Back')

        self.cancel = QPushButton(Form)
        self.cancel.setGeometry(200, 30, 113, 32)
        self.cancel.setText('Cancel')

        self.sendB = QPushButton(Form)
        self.sendB.setGeometry(513, 30, 113, 32)
        self.sendB.setText('Send')

        self.draft = QPushButton(Form)
        self.draft.setGeometry(826, 30, 113, 32)
        self.draft.setText('Save Draft')



        self.back.show()
        self.inbox.show()
        self.compose.show()
        self.sent.show()
        self.scrollAreaWidgetContents.show()
        self.nex.show()
        self.pre.show()
        self.cs.show()
        self.de.show()
        self.label.show()
        self.nm.show()
        self.sa.show()
        self.junk.show()
        self.thrash.show()
        self.search.show()
        self.se = QPushButton(Form)
        self.se.setGeometry(778, 0, 28, 28)
        self.se.setStyleSheet("QPushButton{background-color:rgba(173,216,230,0.4);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("se.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.se.setIcon(icon)
        self.se.show()
        self.out.show()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inbox.setText(_translate("Form", "Inbox"))
        self.compose.setText(_translate("Form", "Compose"))
        self.sent.setText(_translate("Form", "Sent"))
        self.junk.setText(_translate("Form", "Junk"))
        self.thrash.setText(_translate("Form", "Thrash"))
        self.out.setText(_translate("Form", "Log Out"))

